<a href="https://colab.research.google.com/github/nastaranmarzban/BGAT-and-GAT-Jupyter-notebook/blob/main/preprocessing_data_4classdes_100nodes_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount to gdrive to read data, adjacency matrix, p_link and labels.

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


# Install pandas to read csv files from gdrive. Install torch and numpy which are packages that are needed durind coding.

In [ ]:
!pip install pandas
import pandas as pd
import torch
import numpy as np

## It is time to prepare x, edge_index, y, train_mask and test_mask which are needed for PyG.

**Step1 (preparing x)**: Read multivariate dataset from gdrive and convert the type to what is needed in PyG.

In [ ]:
x = pd.read_csv('/gdrive/MyDrive/4classes_100.sim/df1_t.csv', sep = ',',header = None)
x = x.astype(np.float32) #try to cast all DataFrame columns to specified numpy.dtype
x = torch.tensor(x.values) #convert numpy.dtype to a tensor
print(x.sum(dim = 1).unique().size()) #to see if there is a duplicate data in x or not
print(x.dtype)
print(x.type())
print(x.size())
print(x)

torch.Size([100])
torch.float32
torch.FloatTensor
torch.Size([100, 500])
tensor([[-0.2138,  0.1836, -1.2796,  ..., -0.7865,  0.3766, -0.0634],
        [ 0.1939, -1.7053,  0.0836,  ...,  1.9979, -0.0287,  0.2419],
        [ 1.1427, -0.1411, -1.8947,  ..., -1.1283, -2.1305, -0.6967],
        ...,
        [ 0.2675, -1.8261,  0.3187,  ...,  1.4613, -0.2672,  0.4551],
        [ 0.4348, -0.0747, -0.3687,  ..., -0.3990, -0.2855, -0.3294],
        [ 1.1066,  0.3640, -1.1720,  ...,  0.7746,  0.5340, -0.4019]])


**Step2 (preparing edge_index)**: Read adjacency matrix from gdrive and convert the type to what is needed in PyG.

In [ ]:
from scipy.sparse import coo_matrix
edge_index_csv = pd.read_csv('/gdrive/MyDrive/4classes_100.sim/adj_diag_4.csv',sep = ',',header = None)
#print(edge_index_csv)
edge_index_numpy_ndarry = edge_index_csv.values #convert xlsx file to numpy.ndarry
edge_index_coo = coo_matrix(edge_index_numpy_ndarry) #convert symmetric matrix to coo_matrix
print(edge_index_coo)

  (0, 6)	1
  (0, 13)	1
  (0, 20)	1
  (0, 43)	1
  (0, 95)	1
  (1, 5)	1
  (1, 17)	1
  (1, 21)	1
  (1, 31)	1
  (1, 39)	1
  (1, 44)	1
  (1, 71)	1
  (1, 89)	1
  (1, 90)	1
  (1, 96)	1
  (1, 97)	1
  (2, 9)	1
  (3, 94)	1
  (4, 57)	1
  (5, 1)	1
  (5, 17)	1
  (5, 19)	1
  (5, 41)	1
  (5, 44)	1
  (5, 71)	1
  :	:
  (95, 32)	1
  (95, 99)	1
  (96, 1)	1
  (96, 5)	1
  (96, 24)	1
  (96, 39)	1
  (96, 41)	1
  (96, 44)	1
  (96, 63)	1
  (96, 68)	1
  (96, 74)	1
  (96, 83)	1
  (97, 1)	1
  (97, 17)	1
  (97, 21)	1
  (97, 23)	1
  (97, 27)	1
  (97, 39)	1
  (97, 41)	1
  (97, 44)	1
  (97, 63)	1
  (97, 89)	1
  (97, 92)	1
  (98, 58)	1
  (99, 95)	1


In [ ]:
edge_index_numpy = np.vstack((edge_index_coo.row, edge_index_coo.col)) #convert coo_matrix to numpy.ndarray
edge_index_torch_int32 = torch.from_numpy(edge_index_numpy) #convert numpy.ndarray to torch.int32
edge_index = edge_index_torch_int32.to(torch.int64) #convert torch.int32 to torch.long
print(edge_index)
print(edge_index.dtype)
print(edge_index.type())
print(edge_index.size())

tensor([[ 0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  3,
          4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  7,  8,  8,  8,  9,
          9,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, 13, 13, 13, 14, 15, 15, 16,
         16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18,
         18, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 21, 21, 21,
         21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23,
         23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 26, 26, 27,
         27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 31, 31, 31, 31, 31,
         31, 31, 31, 31, 32, 33, 33, 33, 33, 34, 34, 34, 35, 35, 35, 36, 36, 36,
         37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 39, 39, 39, 39,
         39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 41, 41, 41, 41, 41, 41,
         41, 41, 41, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43, 44, 44,
         44, 44, 44, 44, 44,

**Step3 (preparing y)**: Read labels from gdrive and convert the type to what is needed in PyG.

In [ ]:
labels_csv = pd.read_csv('/gdrive/MyDrive/4classes_100.sim/labels.csv',sep = ',',header = None)
y = torch.tensor(labels_csv.values)
y.resize_((100))
print(y)

tensor([0, 1, 3, 3, 3, 1, 0, 3, 3, 3, 2, 2, 2, 0, 3, 2, 2, 1, 3, 1, 0, 1, 2, 1,
        1, 3, 3, 1, 2, 3, 3, 1, 0, 0, 0, 2, 0, 1, 0, 1, 3, 1, 0, 0, 1, 2, 2, 2,
        2, 2, 0, 2, 3, 0, 2, 3, 2, 3, 0, 3, 3, 2, 3, 1, 2, 2, 2, 0, 1, 0, 2, 1,
        0, 0, 1, 2, 2, 3, 0, 2, 3, 0, 1, 1, 0, 0, 0, 2, 3, 1, 1, 0, 1, 3, 3, 0,
        1, 1, 2, 0])


**Step4 (preparing train_mask, test_mask)**: split x and y into train and test set.

In [ ]:
from sklearn.model_selection import train_test_split
main_mask, test_mask, y_main, y_test = train_test_split(x, y,  test_size = 10, random_state = 0, shuffle = True, stratify = y)
train_mask, val_mask, y_train, y_val = train_test_split(main_mask, y_main,  test_size = 10, random_state = 0, shuffle = True, stratify = y_main)
print(train_mask.size())
print(val_mask.size())
print(test_mask.size())
print(train_mask.type())
print(y_train.type())

torch.Size([80, 500])
torch.Size([10, 500])
torch.Size([10, 500])
torch.FloatTensor
torch.LongTensor


## To see how many percent of data belong to each class.

In [ ]:
labels, counts = np.unique(y, return_counts = True)
print(counts/float(len(y)))

[0.26 0.24 0.26 0.24]


In [ ]:
labels, counts = np.unique(y_train, return_counts = True)
print(counts/float(len(y_train)))

[0.25 0.25 0.25 0.25]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_val)))

[0.3 0.2 0.3 0.2]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_test)))

[0.3 0.2 0.3 0.2]


## Preparing train_mask and test_mask based on PyG.

In [ ]:
train_mask = (x.unsqueeze(0) == train_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(train_mask)
print(train_mask.size())
print(sum(train_mask))

val_mask = (x.unsqueeze(0) == val_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(val_mask)
print(val_mask.size())
print(sum(val_mask))

test_mask = (x.unsqueeze(0) == test_mask.unsqueeze(1)).all(dim = 2 ).any(dim = 0)
print(test_mask)
print(test_mask.size())
print(sum(test_mask))

tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True, False,  True,
         True, False,  True,  True,  True, False,  True,  True,  True, False,
        False,  True,  True, False, False,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True, False,  True,  True,  True, False,
        False,  True,  True, False,  True,  True,  True, False,  True,  True])
torch.Size([100])
tensor(80)
tensor([False, False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False

## It is time to use p_link as attentions.

In [ ]:
p_link = pd.read_csv('/gdrive/MyDrive/4classes_100.sim/p_links.csv', sep =',',header = None)
p_link = p_link.astype(np.float32)
p_link = torch.tensor(p_link.values)
#p_link = p_link.to(torch.float32)
print(p_link.size())
print(p_link.dtype)
print(p_link.type())

torch.Size([100, 100])
torch.float32
torch.FloatTensor


# Now everything is ready to develop our GNNs.

# Install torch_geometric.

In [ ]:
import os
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

2.1.0+cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 66.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 42.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


# Save data in order to use it.

In [ ]:
from torch_geometric.data import Data
Data = Data(x = x, edge_index = edge_index, y = y, train_mask = train_mask, val_mask = val_mask, test_mask = test_mask)
print(Data)

Data(x=[100, 500], edge_index=[2, 478], y=[100], train_mask=[100], val_mask=[100], test_mask=[100])


In [ ]:
data_save_name = 'data.pt'
path = F"/gdrive/MyDrive/4classes_100.sim/{data_save_name}"
torch.save(Data.to_dict(), path)

In [ ]:
p_link_save_name = 'p_link.pt'
path = F"/gdrive/MyDrive/4classes_100.sim/{p_link_save_name}"
torch.save(p_link, path)