<a href="https://colab.research.google.com/github/nastaranmarzban/BGAT-and-GAT-Jupyter-notebook/blob/main/preprocessing_data_5classes_200nodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount to gdrive to read data, adjacency matrix, p_link and labels.

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


# Install pandas to read csv files from gdrive. Install torch and numpy which are packages that are needed durind coding.

In [ ]:
!pip install pandas
import pandas as pd
import torch
import numpy as np

## It is time to prepare x, edge_index, y, train_mask and test_mask which are needed for PyG.

**Step1 (preparing x)**: Read multivariate dataset from gdrive and convert the type to what is needed in PyG.

In [ ]:
x = pd.read_csv('/gdrive/MyDrive/5classes_200_non.sim/df1_t_200.csv', sep = ',',header = None)
x = x.astype(np.float32) #try to cast all DataFrame columns to specified numpy.dtype
x = torch.tensor(x.values) #convert numpy.dtype to a tensor
print(x.sum(dim = 1).unique().size()) #to see if there is a duplicate data in x or not
print(x.dtype)
print(x.type())
print(x.size())
print(x)

torch.Size([200])
torch.float32
torch.FloatTensor
torch.Size([200, 500])
tensor([[ 0.1064,  0.0268,  0.0688,  ...,  0.1277,  0.0208,  0.0365],
        [-1.1319,  0.0287, -1.2385,  ..., -0.1471,  1.4365, -0.7657],
        [ 0.5656,  1.3512,  2.0302,  ...,  1.2031, -1.7998,  1.0181],
        ...,
        [-0.0979,  0.9709,  0.6932,  ..., -0.8765, -0.6086, -0.5979],
        [ 1.9060, -0.2760,  1.1493,  ..., -1.1248,  0.7692,  0.6333],
        [ 1.1451, -1.8192, -2.0841,  ...,  1.7384, -0.7770, -0.3205]])


**Step2 (preparing edge_index)**: Read adjacency matrix from gdrive and convert the type to what is needed in PyG.

In [ ]:
from scipy.sparse import coo_matrix
edge_index_csv = pd.read_csv('/gdrive/MyDrive/5classes_200_non.sim/adj_diag_200.csv',sep = ',',header = None)
#print(edge_index_csv)
edge_index_numpy_ndarry = edge_index_csv.values #convert xlsx file to numpy.ndarry
edge_index_coo = coo_matrix(edge_index_numpy_ndarry) #convert symmetric matrix to coo_matrix
print(edge_index_coo)

  (0, 9)	1
  (0, 12)	1
  (0, 20)	1
  (0, 78)	1
  (0, 80)	1
  (0, 130)	1
  (0, 154)	1
  (0, 158)	1
  (1, 35)	1
  (1, 49)	1
  (1, 52)	1
  (1, 70)	1
  (1, 71)	1
  (1, 82)	1
  (2, 4)	1
  (2, 8)	1
  (2, 53)	1
  (2, 69)	1
  (2, 98)	1
  (2, 119)	1
  (2, 127)	1
  (2, 156)	1
  (2, 190)	1
  (3, 17)	1
  (3, 41)	1
  :	:
  (196, 144)	1
  (196, 158)	1
  (197, 21)	1
  (197, 51)	1
  (197, 61)	1
  (197, 68)	1
  (197, 97)	1
  (197, 115)	1
  (197, 139)	1
  (197, 151)	1
  (197, 157)	1
  (198, 22)	1
  (198, 56)	1
  (199, 27)	1
  (199, 32)	1
  (199, 45)	1
  (199, 49)	1
  (199, 55)	1
  (199, 60)	1
  (199, 66)	1
  (199, 70)	1
  (199, 75)	1
  (199, 90)	1
  (199, 100)	1
  (199, 174)	1


In [ ]:
edge_index_numpy = np.vstack((edge_index_coo.row, edge_index_coo.col)) #convert coo_matrix to numpy.ndarray
edge_index_torch_int32 = torch.from_numpy(edge_index_numpy) #convert numpy.ndarray to torch.int32
edge_index = edge_index_torch_int32.to(torch.int64) #convert torch.int32 to torch.long
print(edge_index)
print(edge_index.dtype)
print(edge_index.type())
print(edge_index.size())

tensor([[  0,   0,   0,  ..., 199, 199, 199],
        [  9,  12,  20,  ...,  90, 100, 174]])
torch.int64
torch.LongTensor
torch.Size([2, 1790])


**Step3 (preparing y)**: Read labels from gdrive and convert the type to what is needed in PyG.

In [ ]:
labels_csv = pd.read_csv('/gdrive/MyDrive/5classes_200_non.sim/labels_200.csv',sep = ',',header = None)
y = torch.tensor(labels_csv.values)
y.resize_((200))
print(y)

tensor([2, 3, 4, 4, 4, 4, 0, 4, 4, 2, 3, 4, 1, 0, 2, 3, 1, 4, 3, 0, 0, 1, 1, 1,
        1, 2, 4, 3, 1, 4, 1, 4, 0, 0, 2, 3, 0, 4, 1, 1, 3, 0, 0, 0, 1, 3, 4, 1,
        3, 3, 0, 4, 2, 4, 4, 3, 3, 2, 2, 2, 3, 4, 4, 2, 4, 4, 3, 0, 4, 0, 3, 3,
        0, 0, 1, 2, 4, 2, 0, 4, 4, 4, 2, 0, 0, 2, 0, 4, 0, 2, 3, 3, 2, 2, 3, 2,
        2, 4, 4, 3, 3, 1, 1, 1, 0, 0, 2, 1, 2, 0, 0, 3, 3, 2, 1, 3, 3, 2, 1, 4,
        0, 1, 3, 2, 3, 0, 4, 4, 0, 1, 2, 1, 3, 1, 4, 3, 2, 3, 4, 1, 4, 0, 1, 1,
        2, 1, 2, 0, 3, 4, 2, 2, 2, 2, 3, 0, 4, 1, 2, 1, 2, 0, 0, 3, 0, 0, 0, 1,
        1, 3, 1, 0, 1, 1, 3, 1, 4, 2, 2, 2, 1, 0, 3, 4, 1, 3, 0, 3, 0, 1, 4, 2,
        0, 1, 2, 1, 2, 4, 3, 3])


**Step4 (preparing train_mask, test_mask)**: split x and y into train and test set.

In [ ]:
from sklearn.model_selection import train_test_split
main_mask, test_mask, y_main, y_test = train_test_split(x, y,  test_size = 20, random_state = 0, shuffle = True, stratify = y)
train_mask, val_mask, y_train, y_val = train_test_split(main_mask, y_main,  test_size = 20, random_state = 0, shuffle = True, stratify = y_main)
print(train_mask.size())
print(val_mask.size())
print(test_mask.size())
print(train_mask.type())
print(y_train.type())

torch.Size([160, 500])
torch.Size([20, 500])
torch.Size([20, 500])
torch.FloatTensor
torch.LongTensor


## To see how many percent of data belong to each class.

In [ ]:
labels, counts = np.unique(y, return_counts = True)
print(counts/float(len(y)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_train, return_counts = True)
print(counts/float(len(y_train)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_val)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_test)))

[0.2 0.2 0.2 0.2 0.2]


## Preparing train_mask and test_mask based on PyG.

In [ ]:
train_mask = (x.unsqueeze(0) == train_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(train_mask)
print(train_mask.size())
print(sum(train_mask))

val_mask = (x.unsqueeze(0) == val_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(val_mask)
print(val_mask.size())
print(sum(val_mask))

test_mask = (x.unsqueeze(0) == test_mask.unsqueeze(1)).all(dim = 2 ).any(dim = 0)
print(test_mask)
print(test_mask.size())
print(sum(test_mask))

tensor([ True,  True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True, False, False, False,  True,  True,  True,  True,
         True, False,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True, False,  True, False,  True,  True, False,  True,
         True,  True,  True, False,  True,  True, False,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, 

## It is time to use p_link as attentions.

In [ ]:
p_link = pd.read_csv('/gdrive/MyDrive/5classes_200_non.sim/p_links_200.csv', sep =',',header = None)
p_link = p_link.astype(np.float32)
p_link = torch.tensor(p_link.values)
#p_link = p_link.to(torch.float32)
print(p_link.size())
print(p_link.dtype)
print(p_link.type())

torch.Size([200, 200])
torch.float32
torch.FloatTensor


# Now everything is ready to develop our GNNs.

# Install torch_geometric.

In [ ]:
import os
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

2.1.0+cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 53.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 41.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


# Save data in order to use it.

In [ ]:
from torch_geometric.data import Data
Data = Data(x = x, edge_index = edge_index, y = y, train_mask = train_mask, val_mask = val_mask, test_mask = test_mask)
print(Data)

Data(x=[200, 500], edge_index=[2, 1790], y=[200], train_mask=[200], val_mask=[200], test_mask=[200])


In [ ]:
data_save_name = 'data.pt'
path = F"/gdrive/MyDrive/5classes_200_non.sim/{data_save_name}"
torch.save(Data.to_dict(), path)

In [ ]:
p_link_save_name = 'p_link.pt'
path = F"/gdrive/MyDrive/5classes_200_non.sim/{p_link_save_name}"
torch.save(p_link, path)

In [ ]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create an SVM classifier
clf = svm.SVC(kernel='linear', decision_function_shape='ovr')

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.725


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Create a Random Forest classifier
clf = RandomForestClassifier(n_estimators=500)

# Train the classifier on the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.725


In [ ]:
import numpy as np
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.models import Sequential

# Convert labels to one-hot encoding
y_cat = to_categorical(y)  # Assuming 'y' is your original label array

# Convert PyTorch tensor to NumPy array
X_train_np = x.numpy()  # Assuming 'X_train' is a PyTorch tensor

# Print the shapes of X_train_np and y_cat for debugging
print("X_train_np shape:", X_train_np.shape)
print("y_cat shape:", y_cat.shape)

# Split the data into training and testing sets
X_train_np, X_test, y_train_cat, y_test_cat = train_test_split(X_train_np, y_cat, test_size=0.2, random_state=42)

# Create a neural network model
model = Sequential()
model.add(Dense(12, input_dim=X_train_np.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(5, activation='softmax'))  # 5 classes

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the training data
model.fit(X_train_np, y_train_cat, epochs=100, batch_size=10)

# Make predictions on the test data
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert one-hot encoded labels back to integers for evaluation
y_test = np.argmax(y_test_cat, axis=1)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
import numpy as np
from keras.layers import Dense
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from keras.models import Sequential

# Convert labels to one-hot encoding
y_cat = to_categorical(y)  # Assuming 'y' is your original label array

# Convert PyTorch tensor to NumPy array
X_train_np = x.numpy()  # Assuming 'X_train' is a PyTorch tensor

# Print the shapes of X_train_np and y_cat for debugging
print("X_train_np shape:", X_train_np.shape)
print("y_cat shape:", y_cat.shape)

# Split the data into training and testing sets
X_train, X_test, y_train_cat, y_test_cat = train_test_split(X_train_np, y_cat, test_size=0.2, random_state=42)

# Create a neural network model
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(10, activation='relu'))
#model.add(Dense(16, activation='relu'))
model.add(Dense(5, activation='softmax'))  # 5 classes

# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model on the training data
model.fit(X_train, y_train_cat, epochs=100, batch_size=32, validation_split=0.1)

# Make predictions on the test data
y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)

# Convert one-hot encoded labels back to integers for evaluation
y_test = np.argmax(y_test_cat, axis=1)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


X_train_np shape: (200, 500)
y_cat shape: (200, 5)
Epoch 1/100
5/5 [==============================] - 1s 52ms/step - loss: 1.7284 - accuracy: 0.2500 - val_loss: 1.5061 - val_accuracy: 0.5000
Epoch 2/100
5/5 [==============================] - 0s 9ms/step - loss: 1.3189 - accuracy: 0.5278 - val_loss: 1.3578 - val_accuracy: 0.5625
Epoch 3/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0824 - accuracy: 0.6667 - val_loss: 1.1970 - val_accuracy: 0.6875
Epoch 4/100
5/5 [==============================] - 0s 9ms/step - loss: 0.9240 - accuracy: 0.7153 - val_loss: 1.0588 - val_accuracy: 0.6875
Epoch 5/100
5/5 [==============================] - 0s 9ms/step - loss: 0.8062 - accuracy: 0.7292 - val_loss: 0.9559 - val_accuracy: 0.6875
Epoch 6/100
5/5 [==============================] - 0s 9ms/step - loss: 0.7110 - accuracy: 0.7361 - val_loss: 0.8801 - val_accuracy: 0.6875
Epoch 7/100
5/5 [==============================] - 0s 9ms/step - loss: 0.6310 - accuracy: 0.7500 - val_loss: 0.817