<a href="https://colab.research.google.com/github/nastaranmarzban/BGAT-and-GAT-Jupyter-notebook/blob/main/preprocessing_data_5classdes_150nodes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount to gdrive to read data, adjacency matrix, p_link and labels.

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


# Install pandas to read csv files from gdrive. Install torch and numpy which are packages that are needed durind coding.

In [ ]:
!pip install pandas
import pandas as pd
import torch
import numpy as np

## It is time to prepare x, edge_index, y, train_mask and test_mask which are needed for PyG.

**Step1 (preparing x)**: Read multivariate dataset from gdrive and convert the type to what is needed in PyG.

In [ ]:
x = pd.read_csv('/gdrive/MyDrive/5classes_150.sim/df150_t.csv', sep = ',',header = None)
x = x.astype(np.float32) #try to cast all DataFrame columns to specified numpy.dtype
x = torch.tensor(x.values) #convert numpy.dtype to a tensor
print(x.sum(dim = 1).unique().size()) #to see if there is a duplicate data in x or not
print(x.dtype)
print(x.type())
print(x.size())
print(x)

torch.Size([150])
torch.float32
torch.FloatTensor
torch.Size([150, 500])
tensor([[-1.1996, -0.5363, -1.0551,  ...,  1.0784, -0.1099,  0.6258],
        [ 1.9717,  1.5424,  1.0104,  ..., -0.6536,  2.3499, -0.1438],
        [-0.3870,  0.3711, -1.0519,  ..., -0.6554,  2.1013, -0.8379],
        ...,
        [-1.4236, -1.3652, -1.1248,  ..., -1.0004,  0.0174,  1.6165],
        [-0.5597, -2.0122,  0.3641,  ...,  0.2956, -0.0478, -0.5333],
        [ 0.5681, -0.7714,  0.7749,  ..., -0.5489, -1.6281,  1.2040]])


**Step2 (preparing edge_index)**: Read adjacency matrix from gdrive and convert the type to what is needed in PyG.

In [ ]:
from scipy.sparse import coo_matrix
edge_index_csv = pd.read_csv('/gdrive/MyDrive/5classes_150.sim/adj_diag_150.csv',sep = ',',header = None)
#print(edge_index_csv)
edge_index_numpy_ndarry = edge_index_csv.values #convert xlsx file to numpy.ndarry
edge_index_coo = coo_matrix(edge_index_numpy_ndarry) #convert symmetric matrix to coo_matrix
print(edge_index_coo)

  (0, 21)	1
  (0, 57)	1
  (0, 97)	1
  (1, 21)	1
  (1, 24)	1
  (1, 33)	1
  (1, 47)	1
  (1, 74)	1
  (1, 77)	1
  (1, 116)	1
  (1, 117)	1
  (1, 126)	1
  (1, 145)	1
  (2, 65)	1
  (2, 132)	1
  (2, 148)	1
  (3, 15)	1
  (3, 46)	1
  (3, 61)	1
  (3, 76)	1
  (3, 135)	1
  (4, 29)	1
  (4, 45)	1
  (4, 137)	1
  (5, 17)	1
  :	:
  (145, 116)	1
  (145, 117)	1
  (145, 123)	1
  (145, 130)	1
  (146, 57)	1
  (146, 82)	1
  (146, 97)	1
  (146, 134)	1
  (147, 57)	1
  (147, 93)	1
  (148, 2)	1
  (148, 46)	1
  (148, 49)	1
  (148, 73)	1
  (149, 13)	1
  (149, 20)	1
  (149, 32)	1
  (149, 37)	1
  (149, 41)	1
  (149, 62)	1
  (149, 67)	1
  (149, 88)	1
  (149, 109)	1
  (149, 128)	1
  (149, 141)	1


In [ ]:
edge_index_numpy = np.vstack((edge_index_coo.row, edge_index_coo.col)) #convert coo_matrix to numpy.ndarray
edge_index_torch_int32 = torch.from_numpy(edge_index_numpy) #convert numpy.ndarray to torch.int32
edge_index = edge_index_torch_int32.to(torch.int64) #convert torch.int32 to torch.long
print(edge_index)
print(edge_index.dtype)
print(edge_index.type())
print(edge_index.size())

tensor([[  0,   0,   0,  ..., 149, 149, 149],
        [ 21,  57,  97,  ..., 109, 128, 141]])
torch.int64
torch.LongTensor
torch.Size([2, 954])


**Step3 (preparing y)**: Read labels from gdrive and convert the type to what is needed in PyG.

In [ ]:
labels_csv = pd.read_csv('/gdrive/MyDrive/5classes_150.sim/labels_150.csv',sep = ',',header = None)
y = torch.tensor(labels_csv.values)
y.resize_((150))
print(y)

tensor([2, 1, 3, 4, 4, 1, 0, 4, 4, 2, 4, 3, 1, 0, 2, 4, 2, 1, 3, 0, 0, 1, 2, 1,
        1, 2, 3, 0, 2, 4, 2, 1, 0, 0, 0, 3, 0, 0, 1, 1, 3, 0, 0, 1, 1, 4, 4, 1,
        3, 4, 0, 4, 3, 3, 3, 3, 4, 2, 2, 2, 4, 4, 3, 2, 1, 3, 3, 0, 3, 0, 4, 4,
        0, 0, 1, 2, 4, 1, 0, 4, 1, 3, 2, 0, 0, 4, 1, 3, 0, 4, 2, 2, 3, 2, 4, 3,
        3, 2, 1, 4, 4, 2, 4, 2, 0, 0, 4, 2, 3, 0, 0, 3, 1, 4, 3, 1, 1, 1, 1, 3,
        2, 1, 2, 4, 1, 0, 1, 3, 0, 2, 1, 3, 3, 2, 2, 4, 3, 4, 2, 3, 0, 0, 2, 3,
        1, 1, 2, 2, 4, 0])


**Step4 (preparing train_mask, test_mask)**: split x and y into train and test set.

In [ ]:
from sklearn.model_selection import train_test_split
main_mask, test_mask, y_main, y_test = train_test_split(x, y,  test_size = 15, random_state = 0, shuffle = True, stratify = y)
train_mask, val_mask, y_train, y_val = train_test_split(main_mask, y_main,  test_size = 15, random_state = 0, shuffle = True, stratify = y_main)
print(train_mask.size())
print(val_mask.size())
print(test_mask.size())
print(train_mask.type())
print(y_train.type())

torch.Size([120, 500])
torch.Size([15, 500])
torch.Size([15, 500])
torch.FloatTensor
torch.LongTensor


## To see how many percent of data belong to each class.

In [ ]:
labels, counts = np.unique(y, return_counts = True)
print(counts/float(len(y)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_train, return_counts = True)
print(counts/float(len(y_train)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_val)))

[0.2 0.2 0.2 0.2 0.2]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_test)))

[0.2 0.2 0.2 0.2 0.2]


## Preparing train_mask and test_mask based on PyG.

In [ ]:
train_mask = (x.unsqueeze(0) == train_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(train_mask)
print(train_mask.size())
print(sum(train_mask))

val_mask = (x.unsqueeze(0) == val_mask.unsqueeze(1)).all(dim = 2).any(dim = 0)
print(val_mask)
print(val_mask.size())
print(sum(val_mask))

test_mask = (x.unsqueeze(0) == test_mask.unsqueeze(1)).all(dim = 2 ).any(dim = 0)
print(test_mask)
print(test_mask.size())
print(sum(test_mask))

tensor([ True, False,  True,  True,  True,  True, False,  True, False,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True, False, False,  True,  True,  True,  True,
        False,  True,  True,  True,  True,  True,  True, False,  True,  True,
         True, False,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True, False, False,  True,  True,
         True, False,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True, False, False,  True,
         True, False,  True, False,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True, 

## It is time to use p_link as attentions.

In [ ]:
p_link = pd.read_csv('/gdrive/MyDrive/5classes_150.sim/p_links_150.csv', sep =',',header = None)
p_link = p_link.astype(np.float32)
p_link = torch.tensor(p_link.values)
#p_link = p_link.to(torch.float32)
print(p_link.size())
print(p_link.dtype)
print(p_link.type())

torch.Size([150, 150])
torch.float32
torch.FloatTensor


# Now everything is ready to develop our GNNs.

# Install torch_geometric.

In [ ]:
import os
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

2.1.0+cu118
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 47.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 26.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


# Save data in order to use it.

In [ ]:
from torch_geometric.data import Data
Data = Data(x = x, edge_index = edge_index, y = y, train_mask = train_mask, val_mask = val_mask, test_mask = test_mask)
print(Data)

Data(x=[150, 500], edge_index=[2, 954], y=[150], train_mask=[150], val_mask=[150], test_mask=[150])


In [ ]:
data_save_name = 'data.pt'
path = F"/gdrive/MyDrive/5classes_150.sim/{data_save_name}"
torch.save(Data.to_dict(), path)

In [ ]:
p_link_save_name = 'p_link.pt'
path = F"/gdrive/MyDrive/5classes_150.sim/{p_link_save_name}"
torch.save(p_link, path)