<a href="https://colab.research.google.com/github/nastaranmarzban/BGAT-and-GAT-Jupyter-notebook/blob/main/preprocessing_gene_6_prior.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount to gdrive to read data, adjacency matrix, p_link and labels.


In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


# Install pandas to read csv files from gdrive. Install torch and numpy which are packages that are needed durind coding.

In [ ]:
!pip install pandas
import pandas as pd
import torch
import numpy as np

## It is time to prepare x, edge_index, y, train_mask and test_mask which are needed for PyG.

**Step1 (preparing x)**: Read multivariate dataset from gdrive and convert the type to what is needed in PyG.

In [ ]:
#x = pd.read_csv('/gdrive/MyDrive/gene_150/geneExpression_t_total_100.csv', sep=',',header=None)
#x = pd.read_csv('/gdrive/MyDrive/gene_6_prior/geneExpression_t_total_100.csv', sep=',',header=None)
#x = pd.read_csv('/gdrive/MyDrive/gene_3_prior/geneExpression_t_total_100.csv', sep=',',header=None)


x = pd.read_csv('/gdrive/MyDrive/gene_better/matrix_gen_wr.csv', sep=',',header=None)
x = x.astype(np.float32) #try to cast all DataFrame columns to specified numpy.dtype
x = torch.tensor(x.values) #convert numpy.dtype to a tensor
print(x.sum(dim = 1).unique().size()) #to see if there is a duplicate data in x or not
print(x.dtype)
print(x.type())
print(x)
print(x.size())

torch.Size([89])
torch.float32
torch.FloatTensor
tensor([[ 6.4493,  6.0844,  7.3716,  ...,  8.6918, 10.8691, 11.2004],
        [12.4170, 11.6782, 13.3738,  ...,  9.0700, 10.2089, 10.4571],
        [ 8.1833,  6.4246, 10.5602,  ...,  7.3575,  6.6114,  7.7576],
        ...,
        [ 6.6002,  7.4879,  8.0421,  ...,  9.6510,  8.9851,  9.4696],
        [ 6.6107,  7.4934,  8.0498,  ...,  9.6591,  8.9828,  9.4788],
        [ 6.6001,  7.4911,  8.0561,  ...,  9.6553,  8.9820,  9.4658]])
torch.Size([90, 60])


**Step2 (preparing edge_index)**: Read adjacency matrix from gdrive and convert the type to what is needed in PyG.

In [ ]:
from scipy.sparse import coo_matrix
#edge_index_csv = pd.read_csv('/gdrive/MyDrive/gene_150/adj_gene.csv',sep =',',header = None)
#edge_index_csv = pd.read_csv('/gdrive/MyDrive/gene_3_prior/adj_gene.csv',sep =',',header = None)
#dge_index_csv = pd.read_csv('/gdrive/MyDrive/gene_6_prior/adj_gene.csv',sep =',',header = None)


edge_index_csv = pd.read_csv('/gdrive/MyDrive/gene_better/adj_gene.csv',sep =',',header = None)
edge_index_numpy_ndarry = edge_index_csv.values #convert xlsx file to numpy.ndarry
edge_index_coo = coo_matrix(edge_index_numpy_ndarry) #convert symmetric matrix to coo_matrix
print(edge_index_coo)

  (0, 8)	1
  (0, 10)	1
  (0, 57)	1
  (0, 58)	1
  (0, 76)	1
  (0, 83)	1
  (1, 4)	1
  (1, 17)	1
  (1, 19)	1
  (1, 30)	1
  (1, 42)	1
  (1, 48)	1
  (1, 65)	1
  (2, 17)	1
  (2, 21)	1
  (2, 24)	1
  (2, 27)	1
  (2, 30)	1
  (2, 35)	1
  (2, 76)	1
  (2, 78)	1
  (2, 88)	1
  (3, 7)	1
  (3, 29)	1
  (3, 46)	1
  :	:
  (88, 85)	1
  (88, 86)	1
  (89, 15)	1
  (89, 33)	1
  (89, 46)	1
  (89, 50)	1
  (89, 52)	1
  (89, 55)	1
  (89, 56)	1
  (89, 59)	1
  (89, 62)	1
  (89, 63)	1
  (89, 64)	1
  (89, 67)	1
  (89, 70)	1
  (89, 71)	1
  (89, 73)	1
  (89, 74)	1
  (89, 78)	1
  (89, 81)	1
  (89, 82)	1
  (89, 83)	1
  (89, 85)	1
  (89, 86)	1
  (89, 87)	1


In [ ]:
edge_index_numpy = np.vstack((edge_index_coo.row, edge_index_coo.col)) #convert coo_matrix to numpy.ndarray
edge_index_torch_int32 = torch.from_numpy(edge_index_numpy) #convert numpy.ndarray to torch.int32
edge_index = edge_index_torch_int32.to(torch.int64) #convert torch.int32 to torch.long
print(edge_index)
print(edge_index.dtype)
print(edge_index.type())
print(edge_index.size())

tensor([[ 0,  0,  0,  ..., 89, 89, 89],
        [ 8, 10, 57,  ..., 85, 86, 87]])
torch.int64
torch.LongTensor
torch.Size([2, 1650])


**Step3 (preparing y)**: Read labels from gdrive and convert the type to what is needed in PyG.

In [ ]:
#labels_csv = pd.read_csv('/gdrive/MyDrive/gene_6_prior/labels_gene.csv',sep=',',header=None)
#labels_csv = pd.read_csv('/gdrive/MyDrive/gene_3_prior/labels_gene.csv',sep=',',header=None)

labels_csv = pd.read_csv('/gdrive/MyDrive/gene_better/labels_gene.csv',sep=',',header=None)
y = torch.tensor(labels_csv.values)
y.resize_(90)
print(y)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])


**Step4 (preparing train_mask, test_mask)**: split x and y into train and test set.

In [ ]:
import tensorflow as tf

test_mask_GI = x[0:2,]
val_mask_GI = x[2:4,]
train_mask_GI = x[4:31,]



test_mask_H = x[31:33,]
val_mask_H = x[33:35,]
train_mask_H = x[35:60]




test_mask_hm = x[60:62,]
val_mask_hm = x[62:64,]
train_mask_hm = x[64:91,]


test_mask = np.concatenate([test_mask_GI, test_mask_H, test_mask_hm], axis=0)
test_mask = torch.FloatTensor(test_mask)



val_mask = np.concatenate([val_mask_GI, val_mask_H, val_mask_hm], axis=0)
val_mask = torch.FloatTensor(val_mask)



train_mask = np.concatenate([train_mask_GI, train_mask_H, train_mask_hm],  axis=0)
train_mask = torch.FloatTensor(train_mask)



print(train_mask.type())
print(test_mask.type())
print(val_mask.type())

print(train_mask.size())
print(test_mask.size())
print(val_mask.size())

torch.FloatTensor
torch.FloatTensor
torch.FloatTensor
torch.Size([78, 60])
torch.Size([6, 60])
torch.Size([6, 60])


In [ ]:

label_test_mask_GI = y[0:2]
label_val_mask_GI = y[2:4]
label_train_mask_GI = y[4:31]




label_test_mask_H = y[31:33]
label_val_mask_H = y[33:35]
label_train_mask_H = y[35:60]



label_test_mask_hm = y[60:62]
label_val_mask_hm = y[62:64]
label_train_mask_hm= y[64:91]



y_test = np.concatenate([label_test_mask_GI, label_test_mask_H, label_test_mask_hm],
                            axis=0)
y_val = np.concatenate([label_val_mask_GI, label_val_mask_H, label_val_mask_hm],
                           axis=0)


y_train = np.concatenate([label_train_mask_GI, label_train_mask_H, label_train_mask_hm], axis=0)

print(y_train)
print(y_val)
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2]
[0 0 1 1 2 2]
[0 0 1 1 2 2]


## To see how many percent of data belong to each class.

In [ ]:
labels, counts = np.unique(y, return_counts = True)
print(counts/float(len(y)))

[0.33333333 0.33333333 0.33333333]


In [ ]:
labels, counts = np.unique(y_train, return_counts = True)
print(counts/float(len(y_train)))

[0.33333333 0.33333333 0.33333333]


In [ ]:
labels, counts = np.unique(y_test, return_counts = True)
print(counts/float(len(y_test)))

[0.33333333 0.33333333 0.33333333]


In [ ]:
labels, counts = np.unique(y_val, return_counts = True)
print(counts/float(len(y_val)))

[0.33333333 0.33333333 0.33333333]


## Preparing train_mask and test_mask based on PyG.

In [ ]:
train_mask = (x.unsqueeze(0) == train_mask.unsqueeze(1)).all(dim=2).any(dim=0)
print(train_mask)
print(train_mask.size())
print(sum(train_mask))

val_mask = (x.unsqueeze(0) == val_mask.unsqueeze(1)).all(dim=2).any(dim=0)
print(val_mask)
print(val_mask.size())
print(sum(val_mask))

test_mask = (x.unsqueeze(0) == test_mask.unsqueeze(1)).all(dim=2).any(dim=0)
print(test_mask)
print(test_mask.size())
print(sum(test_mask))

tensor([False, False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True, False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,  True])
torch.Size([90])
tensor(78)
tensor([False, False,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False,  True,

## It is time to use p_link as attentions.

In [ ]:
#p_link = pd.read_csv('/gdrive/MyDrive/gene_150/p_links_gene.csv', sep=',',header=None)
#p_link = pd.read_csv('/gdrive/MyDrive/gene_6_prior/p_links_gene.csv', sep=',',header=None)
#p_link = pd.read_csv('/gdrive/MyDrive/gene_3_prior/p_links_gene.csv', sep=',',header=None)
p_link = pd.read_csv('/gdrive/MyDrive/gene_better/p_links_gene.csv', sep=',',header=None)
p_link = p_link.astype(np.float32)
p_link = torch.tensor(p_link.values)
#p_link = p_link.to(torch.float32)
print(p_link.size())
print(p_link.dtype)
print(p_link.type())

torch.Size([90, 90])
torch.float32
torch.FloatTensor


# Now everything is ready to develop our GNNs.

# Install torch_geometric.

In [ ]:
import os
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git

2.1.0+cu118
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


In [ ]:
from torch_geometric.data import Data
Data = Data(x=x, edge_index=edge_index, y = y, train_mask = train_mask, val_mask = val_mask, test_mask = test_mask)
print(Data)

Data(x=[90, 60], edge_index=[2, 1650], y=[90], train_mask=[90], val_mask=[90], test_mask=[90])


# Save data in order to use it.

In [ ]:
data_save_name = 'gene.pt'
#path = F"/gdrive/MyDrive/gene_150/{data_save_name}"
#path = F"/gdrive/MyDrive/gene_6_prior/{data_save_name}"
#path = F"/gdrive/MyDrive/gene_3_prior/{data_save_name}"

path = F"/gdrive/MyDrive/gene_better/{data_save_name}"
torch.save(Data.to_dict(), path)

In [ ]:
p_link_save_name = 'p_links_gene.pt'
#path = F"/gdrive/MyDrive/gene_150/{p_link_save_name}"
#path = F"/gdrive/MyDrive/gene_6_prior/{p_link_save_name}"
#path = F"/gdrive/MyDrive/gene_3_prior/{p_link_save_name}"

path = F"/gdrive/MyDrive/gene_better/{p_link_save_name}"
torch.save(p_link, path)